### ISSUE TITLE
When Filtering for an all numeric host_name returns empty

### ISSUE THREAD

**Issue by openglx** [shinken-monitoring/mod-livestatus#39]
I've identified this on a Shinken 2.0.3 install (pip) on CentOS 6.5 x86_64 (Python 2.6.6, CherryPy 3.2.2). We have mod_livestatus and logsqlite enabled on a environment with realms and complete_broker_links enabled, but probably reproducible in the simplest environment possible.

When you query LiveStatusAPI to "GET hosts" and add "Filter: host_name = (all numeric host name)" it returns empty:

 echo -e "GET hosts\nFilter: host_name = 19910200\n\n" | nc 0 50000 | hexdump
0000000 000a                                   
0000001
(only one new line returned)

If your host_name has any non-numeric character (doesn't need to be the first), then it returns OK:

echo -e "GET hosts\nFilter: host_name = 00-12300\n\n" | nc 0 50000 | hexdump
0000000 6361 6563 7470 705f 7361 6973 6576 635f
0000010 6568 6b63 3b73 6361 6e6b 776f 656c 6764
0000020 6465 613b 6b63 6f6e 6c77 6465 6567 656d
(several lines of output, meaning a complete output)

(NB: use of "hexdump" was just to clarify the output)

I suspect that we are not forcing the "equals to" comparison to be full text ("string"), then something internal fails.

*Workaround*: I've changed my comparison to be a regular expression (symbol ~) and it now works:

 echo -e "GET hosts\nFilter: host_name ~ 19910200\n\n" | nc 0 50000 | hexdump
0000000 6361 6563 7470 705f 7361 6973 6576 635f
0000010 6568 6b63 3b73 6361 6e6b 776f 656c 6764
0000020 6465 613b 6b63 6f6e 6c77 6465 6567 656d
(several lines of output, meaning a complete output)

**Comment by gst** [comment]
I agree that defining an (shinken-)host with only digits in its host_name attribute is rather risky.. for the reason that @olivierHa mention and for the fact that it raised this bug in LS. I'm quite sure it would have others negative consequences in others components of Shinken itself but also with others external softwares connected in a way or another to Shinken.

So I'd be in favor of requesting @openglx to not have shinken-hosts defined with an all numeric host_name... what about simply prefixing all your hosts with (say) "host-" ??

**Comment by openglx** [comment]
@gst I concur, and thus I'm closing this issue as WONTFIX - it is not a bug but a misconfiguration from my side.

Thanks all for your analysis.
