### ISSUE TITLE
[2.2] do you plan to publish the latest livestatus module on shinken.io ? 

### ISSUE THREAD

**Issue by david-guenault** [shinken-monitoring/mod-livestatus#45]

**Comment by Seb-Solon** [comment]
As you may know the issue comes from the cli. @naparuba was the firstto publish it, no one else can do it I think. I tried to do it this morning but the tarball was not updated. (see IRC logs)

**Comment by naparuba** [comment]
done :)

On Tue, Jan 20, 2015 at 6:41 PM, Sébastien Coavoux <notifications@github.com

**Comment by gst** [comment]
Shall web close ?

**Comment by naparuba** [comment]
yep
