### ISSUE TITLE
Shinken 2.0.3 is trying to download livestatus 1.2 (which breaks)

### ISSUE THREAD

**Issue by lostmimic** [shinken-monitoring/mod-livestatus#46]
```
~$ shinken --config=/etc/shinken/shinken.ini install --version
shinken 2.0.3
~$ shinken --config=/etc/shinken/shinken.ini install --download-only livestatus && zgrep -a '"version' /tmp/livestatus.tar.gz
Grabbing : livestatus
Download OK: /tmp/livestatus.tar.gz
  "version": "1.2"
```

Is there a way to limit the version as 2.2 is currently having some issues with our configurations?

**Comment by Seb-Solon** [comment]
shinken cli only download what is on shinken.io. It is a simple tool not a package manager. There is no version history on shinken.io. You have to upgrade on shinken 2.2 or take another version of livestatus from this git. Try 1.0.1 or 1.0

**Comment by lostmimic** [comment]
Thanks, ill adjust the scripts to pull from git and do a local install. (cant go to 2.2 right now due to https://github.com/naparuba/shinken/issues/1468)
