### ISSUE TITLE
Problem Backend: live_1. The object doesn't exist

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-livestatus#69]
Hi,
I installed Nagvis and livestatus module. In Nagvis i created a simple map. I have my hosts and services from Shinken. But i have this error:
![nagvis_a](https://cloud.githubusercontent.com/assets/15362041/12679981/abb77572-c6a7-11e5-890a-8ed98b4a63a3.png)

So i think it's a bad config in bakend in nagvis. How do a  correct configure of backend ? 
Using mklivestatus ? 
![backend](https://cloud.githubusercontent.com/assets/15362041/12680092/4690c35a-c6a8-11e5-8f6c-3cd7612dde04.PNG)

I using Nagvis 1.9b4
My livestatus is on default configuration (port: 50000)
Thx

**Comment by xsylx** [comment]
I have the same pb, with hostgroup (servicegroups too). Service, hosts works great.
Nagvis : 1.8.5
Shinken : 2.4.2

**Comment by Azef1** [comment]
Please why this error ?
I confirm too Hosts and Service works great but not for hostgroup and servicegroup.
The error is the same: Problem (Backend: live_1): The object ... doesn't exist

**Comment by Azef1** [comment]
It's fixed !!!
See https://github.com/shinken-monitoring/mod-livestatus/issues/15 
I edited this var/lib/shinken/modules/livestatus/mapping.py and add staleness for host and service.
I confirm it's works with Nagvis 1.9b4.
I think the livestatus module need a update
